### ISSUE TITLE
Running SQLancer on DuckDB in the CI frequently results in a crash

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#114]
Currently, the Travis CI gate fails every two to three runs, since SQLancer seems to trigger a crash bug in DuckDB. I assume this is already fixed in DuckDB, but has not yet been propagated to the latest Maven JDBC driver. @hannesmuehleisen is a release planned for the near future?

**Comment by hannesmuehleisen** [comment]
Yes it is planned in fact we are a bit overdue. Will make one next week.

**Comment by mrigger** [comment]
Great, thanks!

**Comment by hannesmuehleisen** [comment]
Did 0.2.0 fix the issue?

**Comment by mrigger** [comment]
I didn't observe the issue in the last couple of PRs, so I believe 0.2.0 did fix the issue. Thanks!
