### ISSUE TITLE
sqlancer/mysql/gen/MySQLInsertGenerator.java

### ISSUE THREAD

**Issue by pisces225** [sqlancer/sqlancer#12]
Query generateInto()

for (int row = 0; row < nrRows; row++) {
            if (row != 0) {
                sb.append(", ");
            }
            sb.append("(");
            for (int c = 0; c < columns.size(); c++) {
                if (c++ != 0) {  <----  typo, should be c
                    sb.append(", ");
                }
                sb.append(MySQLVisitor.asString(gen.generateConstant()));

            }
            sb.append(")");
        }

**Comment by mrigger** [comment]
Thanks a lot for pointing this out! Do you want to create a PR to fix this, or should I do it? Either is fine for me.
