### ISSUE TITLE
Disabled ClickHouse CI

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#121]
In https://github.com/sqlancer/sqlancer/pull/101, we disabled the ClickHouse CI due to some new failures that blocked us from merging the PR. We should fix the issue and enable the CI again as soon as possible, to prevent that we break the ClickHouse implementation during refactoring.

**Comment by qoega** [comment]
Actually the problem should be already fixed in https://github.com/ClickHouse/ClickHouse/pull/12426
I'll check if it is already available in docker
