### ISSUE TITLE
Request: print a help list on running the jar with no arguments

### ISSUE THREAD

**Issue by zhangysh1995** [sqlancer/sqlancer#184]
Do not know how to use the tool if no help information is provided, suggest to give a `--help` or `-h` option first.

**Comment by mrigger** [comment]
Actually, running the JAR with no arguments already results in such a list being printed:

```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar 
Usage: SQLancer [options] [command] [command options]
  Options:
    --exit-code-error
      The exit code that should be returned when an error is encountered (or a 
      bug is found)
      Default: -1
    --log-each-select
      Logs every statement issued
      Default: true
...
```
Or did I misunderstand your request?

**Comment by mrigger** [comment]
Would it be desirable to have a `-h` or `--help` command in addition?

**Comment by zhangysh1995** [comment]
I think the explicit options will help!

**Comment by mrigger** [comment]
Okay, I will implement that. Thanks for the suggestion!

**Comment by mrigger** [comment]
SQLancer now supports this.
