### ISSUE TITLE
[Question] How to pass MySQL connection configuration?

### ISSUE THREAD

**Issue by zhangysh1995** [sqlancer/sqlancer#185]
I see an option `--username`, it is also possible to specify the host, port and usage of password? Thank you!

**Comment by zhangysh1995** [comment]
It seems you are already working on this issue, as stated in #95, should I close or leave this open?

**Comment by zhangysh1995** [comment]
Could you please point me to the source code where specifies the default configurations? I will change it locally as a workaround first.

**Comment by mrigger** [comment]
Let's close this one, since the other one already explains the issue.

As a workaround, you can modify the following string:

https://github.com/sqlancer/sqlancer/blob/d750ffe5e23c345859127dee22867969da706680/src/sqlancer/mysql/MySQLProvider.java#L168
