### ISSUE TITLE
Unused port variable in PostgresProvider

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#209]
UCDetector (see http://www.ucdetector.org/) just detected that the `port` variable in the `PostgresProvider` class is never read. @nukoyluoglu, should I delete the variable or do you want to fix this?

https://github.com/sqlancer/sqlancer/blob/2f5ebb2726e86bdc538c8e5b34d15fc425736cca/src/sqlancer/postgres/PostgresProvider.java#L238

**Comment by nukoyluoglu** [comment]
I think you can delete it, the `host` variable also might be redundant
