### ISSUE TITLE
Citus "direct joins between distributed and local tables are not supported" error

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#215]
The Travis CI tests [just failed](https://travis-ci.com/github/sqlancer/sqlancer/jobs/384357212) with an error `direct joins between distributed and local tables are not supported` for a query `SELECT t4.c1, t4.c0 FROM ONLY t4 RIGHT OUTER JOIN (SELECT 0.79263866 FROM ONLY t2, t0*, t1, ONLY t4 LIMIT 5032437055157358207) AS sub0 ON upper((1422540800)::VARCHAR(710))!~*upper((('pt')||((0.0034468356)::MONEY)));` @nukoyluoglu, do you want to fix this or should I add the error to the list of expected errors?

**Comment by nukoyluoglu** [comment]
I think it could be added to expected errors for now. @thanodnl
