### ISSUE TITLE
[Bug] More than 30G virtual memory is used

### ISSUE THREAD

**Issue by zhangysh1995** [sqlancer/sqlancer#236]
Sqlancer has unreasonable virtual memory usage when running:

![image](https://user-images.githubusercontent.com/8340592/95946400-08d6c500-0e1f-11eb-929b-2505c14d2b1d.png)

![image](https://user-images.githubusercontent.com/8340592/95946439-1c822b80-0e1f-11eb-8a57-c8c54855dd9a.png)

**Comment by mrigger** [comment]
After an offline discussion, a likely reason seems to be that the JVM allocates that much memory for a machine with much memory.
