### ISSUE TITLE
Add a testing implementation for TimescaleDB

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#24]
Mike Freedman, CTO and Co-founder of Timescale, [expressed interest in having TimescaleDB tested](https://twitter.com/michaelfreedman/status/1264752236644761605):

> Hey Manuel: would welcome any testing to @TimescaleDB , which is implemented as extension to Postgres and thus probably already fits your model.

The implementation could probably be based on top of SQLancer's PostgreSQL implementation.

**Comment by Ethan-DB** [comment]
What is it different from PostgreSQL? Whether it can share the same set of tests with Postgres? And add the `time travel` function on this Postgres test. @mrigger

**Comment by GoswamiTushar** [comment]
Hi, can I work on this issue?

**Comment by amangupta201** [comment]
Hey could you please assign me this issue?
