### ISSUE TITLE
Confusions about generating queries with specific oracle

### ISSUE THREAD

**Issue by xinyuliu12** [sqlancer/sqlancer#270]
I was wondering which `--oracle` parameter I need to use if my goal is to test DBMSs only using Ternary Logic Query Partitioning (TLP):
`java -jar SQLancer-0.0.1-SNAPSHOT.jar --num-threads 4 sqlite3 --oracle NoREC` (according to the Quick Start Guide)
or
`java -jar SQLancer-0.0.1-SNAPSHOT.jar --num-threads 4 sqlite3 --oracle QUERY_PARTITIONING` (according to my understanding of the SQLite3Options.java).

**Comment by mrigger** [comment]
Thanks for pointing this out! The description has been fixed in https://github.com/sqlancer/sqlancer/commit/02a52bf2e73e9ab3d6cd77ca64b85a719236c3b2. To use TLP, the `QUERY_PARTITIONING` oracle option is the correct one.
