### ISSUE TITLE
How do work  sqlancer with intellij idea

### ISSUE THREAD

**Issue by xlw712** [sqlancer/sqlancer#273]
hi 
    I try using intellij build , but build print error ! below
     Error:java: java.lang.IllegalArgumentException: properties file .settings/org.eclipse.jdt.core.prefs does not exist
     Error:java: properties file .settings/org.eclipse.jdt.core.prefs does not exist
  
Is there any way to solve it

**Comment by xlw712** [comment]
Oh I'm work in the MaxOS

**Comment by mrigger** [comment]
Thanks for opening the issue!

Could you please try to replace `.settings/org.eclipse.jdt.core.prefs` by `${project.basedir}/.settings/org.eclipse.jdt.core.prefs` in the `pom.xml` file, and tell me whether this solved the issue? If that does not work, as a workaround, you could remove the line `<properties>${project.basedir}/.settings/org.eclipse.jdt.core.prefs</properties>` from this file.

https://github.com/sqlancer/sqlancer/blob/547280b2d9c8ff8de0790c9f22498a56c17e59fd/pom.xml#L46

**Comment by qoega** [comment]
I fixed it the same way:
``` xml
            <properties>${project.basedir}/.settings/org.eclipse.jdt.core.prefs</properties>
```

**Comment by mrigger** [comment]
Great, since this works, I created a PR and merged the change.
