### ISSUE TITLE
mvn package fails with Ubuntu 20.04 and openjdk-14-jdk

### ISSUE THREAD

**Issue by qoega** [sqlancer/sqlancer#288]
My current docker image with recent changes stopped to build.
Report
https://clickhouse-test-reports.s3.yandex.net/19363/4ac080b2cab41ec3e2133eabd017bc505ef59fac/push_to_dockerhub.html#fail1
build log
https://clickhouse-test-reports.s3.yandex.net/19363/4ac080b2cab41ec3e2133eabd017bc505ef59fac/push_to_dockerhub/dockerbuild.out.9.log

I can reproduce it simply by running in clickhouse/docker/test/sqlancer
```docker build -t yandex/clickhouse-sqlancer ```
Source code:
https://github.com/ClickHouse/ClickHouse/tree/master/docker/test/sqlancer

On MacOS I do not have that issue.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  36.807 s
[INFO] Finished at: 2021-01-21T15:58:30Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project sqlancer: MavenReportException: Error while generating Javadoc: Unable to find javadoc command: The environment variable JAVA_HOME is not correctly set. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
The command '/bin/sh -c cd /sqlancer/sqlancer-master && mvn clean && echo $JAVA_HOME && mvn package -DskipTests -DskipDocs' returned a non-zero code: 1
```

**Comment by mrigger** [comment]
Sorry, I'm investigating this now.

**Comment by qoega** [comment]
Actually it is not a big issue. We just can't take the latest version, but still run current one and continue to find more bugs.

**Comment by mrigger** [comment]
It seems to work now. The Docker Image executes without errors after merging the PR. It might be safer at the moment to check out a version of SQLancer that is known to work. I'm currently working on making (Maven) releases work, so in the future, building SQLancer will no longer be required when it is used in a CI.

**Comment by qoega** [comment]
Thanks! It works: https://clickhouse-test-reports.s3.yandex.net/19363/a623084eb008d5d85055ec59e7184d43c16eb230/push_to_dockerhub.html

That is true. Currently I just added a simple way to run it and add it to our CI. There were other things to be done to create report, check for failures etc.
We now have this for each commit to master branch. 
https://clickhouse-test-reports.s3.yandex.net/0/7370335f872063b56d6efa881cacac98edc97616/sqlancer_test.html
And we also store all test statuses to ClickHouse for further analytics. SQLancer results are also stored in DB.

As soon as there will be releases, I'll just change this docker file and it will continue to work.
