### ISSUE TITLE
Compilation failed in IntelliJ IDEA

### ISSUE THREAD

**Issue by gfphoenix78** [sqlancer/sqlancer#374]
I can't compile sqlancer(master branch) in Intellij IDEA on MacOSX.

JDK version: 1.8.0_291
sqlancer branch: master (commit 29d2179d543774eeaecd8fc77dd)
Intellij IDA version: 2018.2

Error messages:
```
Information:java: Errors occurred while compiling module 'sqlancer'
Information:javac 1.8.0_291 was used to compile java sources
Information:7/19/21, 2:57 PM - Compilation completed with 10 errors and 2 warnings in 4 s 584 ms
/Users/hawu/workspace/sqlancer/src/sqlancer/mongodb/MongoDBOptions.java
Error:(53, 49) java: cannot find symbol
  symbol:   class OracleFactory
  location: class sqlancer.mongodb.MongoDBOptions
Error:(19, 74) java: type argument sqlancer.mongodb.MongoDBOptions.MongoDBOracleFactory is not within bounds of type-variable F
Error:(55, 13) java: method does not override or implement a method from a supertype
Error:(63, 13) java: method does not override or implement a method from a supertype
/Users/hawu/workspace/sqlancer/src/sqlancer/arangodb/ArangoDBOptions.java
Error:(37, 50) java: cannot find symbol
  symbol:   class OracleFactory
  location: class sqlancer.arangodb.ArangoDBOptions
Error:(17, 76) java: type argument sqlancer.arangodb.ArangoDBOptions.ArangoDBOracleFactory is not within bounds of type-variable F
Error:(39, 13) java: method does not override or implement a method from a supertype
/Users/hawu/workspace/sqlancer/src/sqlancer/mongodb/MongoDBProvider.java
Error:(25, 69) java: type argument sqlancer.mongodb.MongoDBOptions is not within bounds of type-variable O
/Users/hawu/workspace/sqlancer/src/sqlancer/arangodb/ArangoDBProvider.java
Error:(23, 71) java: type argument sqlancer.arangodb.ArangoDBOptions is not within bounds of type-variable O
/Users/hawu/workspace/sqlancer/src/sqlancer/mongodb/MongoDBLoggableFactory.java
Warning:(22, 21) java: commentOutQuery(sqlancer.common.query.Query<?>) in sqlancer.common.log.LoggableFactory has been deprecated
/Users/hawu/workspace/sqlancer/src/sqlancer/arangodb/ArangoDBLoggableFactory.java
Warning:(22, 21) java: commentOutQuery(sqlancer.common.query.Query<?>) in sqlancer.common.log.LoggableFactory has been deprecated
/Users/hawu/workspace/sqlancer/src/sqlancer/cosmos/CosmosProvider.java
Error:(21, 78) java: type argument sqlancer.mongodb.MongoDBOptions is not within bounds of type-variable O
```

**Comment by oraluben** [comment]
I didn't meet such an issue, would you please describe how you compile SQLancer in IDEA?

**Comment by gfphoenix78** [comment]
@oraluben  Well, I first run **`mvn package -DskipTests`** to build sqlancer(and download its dependencies) and then simply open sqlancer in Intellij IDEA.
The IDE doesn't show any error. But when I run the main function **`Main.main()`**, it shows the above error messages.

After applying the patch(https://github.com/sqlancer/sqlancer/pull/375), IDEA successfully runs sqlancer to test the database as expected.

**Comment by oraluben** [comment]
IDEA has maven integration and I'm able to just clone the repo from scratch and open it in IDEA as well as run `Main.main()`, by clicking the arrow near the function.

Have you tried upgrading IDEA (or JDK)? I've tested against JDK 1.8.0_302-b08 and IDEA 2021.1.3.

**Comment by gfphoenix78** [comment]
I use MacOSX, the suggested version of java is `1.8.0_291`. After upgrading IDEA to 2021.1.3, the failure still exists. It's better to fix this issue in the code, not by upgrading JDK to the latest version.

**Comment by mrigger** [comment]
Thanks for PR #375, which fixed this. Since the change was not invasive and simplified the code a bit, I think it is useful to do this change in each case.
