### ISSUE TITLE
Postgres Deprecated "vacuum_cleanup_index_scale_factor" Parameter

### ISSUE THREAD

**Issue by halilozanakgul** [sqlancer/sqlancer#400]
The `vacuum_cleanup_index_scale_factor` parameter is removed from Postgres but it is still used in `PostgresSetGenerator.java` file.
Because of this, running Citus tests with Postgres 14 sometimes fails.

Maybe a version control mechanism is necessary.
Or if only the latest version is supported, this parameter might need to be removed.

**Comment by mrigger** [comment]
I think we could remove this from the Postgres implementation now, given that we will have to remove it anyway when we upgrade to the latest PostgreSQL version. Do you want to open a PR for that or should I look into this later?

**Comment by halilozanakgul** [comment]
I can open a PR.
