### ISSUE TITLE
Test or Remove the Document Stores (MongoDB, ArangoDB, and Cosmos)

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#442]
The document stores (introduced in https://github.com/sqlancer/sqlancer/pull/319) are currently neither actively used nor tested in the CI. For maintainability, it would be useful to either test or remove them. For now, we should instruct Dependabot to not update the dependencies with the known-working versions.

**Comment by malwaregarry** [comment]
the databases were removed in https://github.com/sqlancer/sqlancer/pull/915 as they resulted in difficulty refactoring SQLancer.
