### ISSUE TITLE
Has someone applied sqlancer to PartiQL?

### ISSUE THREAD

**Issue by ankushdesai** [sqlancer/sqlancer#503]
Was just curious if there has been past work on applying sqlancer to PartiQL?
https://partiql.org/

**Comment by mrigger** [comment]
It would be great to try that! I haven't and I'm not aware of anyone working on this. It would likely make it easier (but not necessary) to support PartiQL if it had a JDBC driver. From https://github.com/partiql/partiql-lang-kotlin/issues/240, I see that an experimental JDBC driver exists, but is not actively maintained, right?

Is this something that you would like to try or that someone else could work on? In the former case, I would be happy to provide feedback. In the latter, I could help publicize that there is an interest in adding support for PartiQL in SQLancer.

**Comment by ankushdesai** [comment]
Thanks for your response. I am interested in both, it would be great if someone else could work on it (in which case we can just use it). If not, I would like to give it a shot and would appreciate your help and feedback on it.
