### ISSUE TITLE
sqlancer for Postgresql doesn't work

### ISSUE THREAD

**Issue by AlexWonga** [sqlancer/sqlancer#533]
hi, I got a problem when I used Sqlancer to generate statements to test Postgresql. I have tried Postgres version 11.16, 12.11, 14.4 but got the same result.
the command I executed is:
`java -jar sqlancer-2.0.0.jar --username "xxxxx" --password "xxxxx" postgres --oracle anyoracle`
Sqlancer can connect to the database. however, it generated complex CREATE statements and most CREATE statements can't execute in Postgresql.

the CREATE statements example:
`CREATE UNLOGGED TABLE t0(c0 REAL  DEFAULT (0.5766932) UNIQUE CHECK ((0.5766932) IN (t0.c0, t0.c0, lower((('(533362188,533362188]'::int4range)+('(-1653413019,1475835678]'::int4range))))) NO INHERIT NULL, c1 TEXT COLLATE "C"  UNIQUE NULL CHECK ((substr(t0.c1, ('(-1653413019,777148101]'::int4range)::INT, strpos(t0.c1, t0.c1))) IS NOT NULL) PRIMARY KEY) WITH (autovacuum_enabled=1, autovacuum_vacuum_scale_factor=0.1, autovacuum_vacuum_cost_limit=934, fillfactor=65, parallel_workers=46, autovacuum_vacuum_threshold=2006834923, autovacuum_freeze_min_age=23860164, autovacuum_analyze_threshold=1082973204);`

as you can see, it is quite complex and strange. Sqlancer reports bugs and stops generating more statements.

what mistake did I make? How to generate executable statements?

**Comment by mrigger** [comment]
It is not unexpected that some `CREATE` statements generated are complex.

What do you mean exactly by "can't execute"? SQLancer might generate statements that are syntactically correct, but not semantically. For example, it does not prevent that duplicate values are inserted into a column with a `UNIQUE` constraint, as preventing such cases would take quite some care and effort. It is unexpected, though, that SQLancer reports bugs and stops generating more statements. Could you post an example of a stacktrace?

**Comment by AlexWonga** [comment]
almost all the CREATE that sqlancer generated have bugs in postgresql. Sqlancer created 100 databases and all of them report bugs about CREATE statements, I believe it is not normal.
for example :
CREATE STATEMENT:
```
CREATE UNLOGGED TABLE IF NOT EXISTS t0(c0 REAL  PRIMARY KEY UNIQUE NOT NULL, c1 BIT VARYING(406) ) WITH (autovacuum_freeze_table_age=1811850877, autovacuum_vacuum_cost_limit=572, autovacuum_freeze_min_age=201224447, autovacuum_enabled=1, fillfactor=18, autovacuum_freeze_max_age=1735614012, autovacuum_analyze_scale_factor=0.9, autovacuum_vacuum_scale_factor=0.1, autovacuum_vacuum_cost_delay=31, parallel_workers=833, autovacuum_analyze_threshold=2123146073, autovacuum_vacuum_threshold=506589930); -- 744ms;
CREATE TEMP TABLE IF NOT EXISTS t1(c0 integer , c1 TEXT , FOREIGN KEY (c0, c1) REFERENCES t0(c0, c1) MATCH FULL ON DELETE SET DEFAULT) PARTITION BY HASH((CAST(0.48329648 AS MONEY))oid_ops, ((+ (t1.c0))::BOOLEAN)) WITH (autovacuum_analyze_threshold=193744989);
```

BUG stacktrace:
```
--java.lang.AssertionError: CREATE TEMP TABLE IF NOT EXISTS t1(c0 integer , c1 TEXT , FOREIGN KEY (c0, c1) REFERENCES t0(c0, c1) MATCH FULL ON DELETE SET DEFAULT) PARTITION BY HASH((CAST(0.48329648 AS MONEY))oid_ops, ((+ (t1.c0))::BOOLEAN)) WITH (autovacuum_analyze_threshold=193744989);
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:100)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:93)
--	at sqlancer.Main$QueryManager.execute(Main.java:227)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
--	at sqlancer.postgres.PostgresProvider.createTables(PostgresProvider.java:306)
--	at sqlancer.postgres.PostgresProvider.generateDatabase(PostgresProvider.java:197)
--	at sqlancer.postgres.PostgresProvider.generateDatabase(PostgresProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:40)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:315)
--	at sqlancer.Main$2.run(Main.java:492)
--	at sqlancer.Main$2.runThread(Main.java:474)
--	at sqlancer.Main$2.run(Main.java:465)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:834)
--Caused by: org.postgresql.util.PSQLException: ERROE: Unrecognized parameter "autovacuum_analyze_threshold"
--	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
--	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
--	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
--	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:329)
--	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:315)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:291)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:286)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:87)
--	... 13 more
```
all 100 databases have different bug reports about CREATE statements, the others like : 
Error: cannot convert type money to int4range; 
Index 0 out of bounds for length 0; 
Error: Unrecognized parameter "autovacuum_vacuum_scale_factor"

after reporting bugs about CREATE statements , SQLancer stops generating statements, so all the Statements that Sqlancer generated are CREATE statements and they have bugs, I can't generate any SELECT statements for test postgresql.

**Comment by AlexWonga** [comment]
steps to reproduce this problem:
1. clone sqlancer 
2. mvn package -DskipTests
3. type command: `java -jar sqlancer-*.jar --username "your-user-name"` --password "--your-password" postgres --oracle anyoracle.
I didn't change any code in sqlancer. 
and sqlancer report like this:
![image](https://user-images.githubusercontent.com/52265703/179709855-7ea769ee-b657-4381-9af1-72a6d414aea5.png)

**Comment by mrigger** [comment]
The `PSQLException` error message seems to be in Chinese, which might be (at least part of) the problem. SQLancer ignores errors assuming that the locale is set to English. Could you perhaps start Postgres while setting the locale to English? Having a look at https://www.postgresql.org/docs/current/locale.html, I believe that at least `LC_MESSAGES` needs to be changed.

**Comment by AlexWonga** [comment]
thanks a lot!! it works.

**Comment by mrigger** [comment]
Great, let me know if you run into any other issues later on.
