### ISSUE TITLE
Not a bug but a question

### ISSUE THREAD

**Issue by St-elin** [sqlancer/sqlancer#563]
Hello!

Thanks a lot for a great tool you've made!

Here's a question:

Let's assume we found a bug with sqlancer after several minutes and covered not much execution paths.

Is there any possibility to ignore the bug or to remember the syntax and queries list, which lead to the bug and do not use it in further generation?

To be more specific, I use sqlancer for postgres.

Thx in advance!

**Comment by oraluben** [comment]
>remember the syntax and queries list

AFAICT no. I think the most common way is to delete the (suspicious) logic that generates the query and rerun the tool, until the bug's fixed in upstream.

**Comment by St-elin** [comment]
Yep, thought so =(
Thanks for the answer
