### ISSUE TITLE
Databend failing CI tests

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#585]
@hanyisong: Can we disable the CI tests for now? I think it might be a better idea, after all, to keep the CI tests green. We can re-enable them once the issues in Databend have been fixed. Alternatively, can we prevent generating problematic patterns for now to avoid CI failures?

**Comment by hanyisong** [comment]
https://github.com/sqlancer/sqlancer/pull/583#issuecomment-1272877443

@mrigger I can reproduce this problem by reopening pr, it fails in the mvn verify phase, not the databend problem

**Comment by mrigger** [comment]
The Databend CI tests fail frequently with the following error:

```
mysql-client is already the newest version (8.0.30-0ubuntu0.20.04.2).
0 upgraded, 0 newly installed, 0 to remove and 47 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     19      0 --:--:-- --:--:-- --:--:--    19

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```
I assume this might indicate some error with the download?

**Comment by hanyisong** [comment]
> The Databend CI tests fail frequently with the following error:
> gzip: stdin: not in gzip format
> tar: Child returned status 1
> tar: Error is not recoverable: exiting now
> Error: Process completed with exit code 2.
>
> I assume this might indicate some error with the download?

YES, This is a problem with the process of downloading the databend. 
When the download is successful, the following information is displayed:
(ref: https://github.com/sqlancer/sqlancer/actions/runs/3222424613/jobs/5271481654#step:5:64)
```
0 upgraded, 0 newly installed, 0 to remove and 41 not upgraded.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

 68  186M   68  128M    0     0   121M      0  0:00:01  0:00:01 --:--:--  121M
100  186M  100  186M    0     0   135M      0  0:00:01  0:00:01 --:--:--  184M
curl: Saved to filename 'databend-v0.8.68-nightly-x86_64-unknown-linux-musl.tar.gz'
```

**Comment by mrigger** [comment]
It would be great if we could try this, given that this issue occurs quite frequently.

**Comment by Xuanwo** [comment]
Let me help fix this.

The CI failed because databend depends on Github Action to build releases. It's possible that the release is not ready for the latest tag.

**Comment by mrigger** [comment]
This seems to no longer reproduce, so closing this issue. Thanks!
