### ISSUE TITLE
The local log file is inconsistent with the log printed on the terminal

### ISSUE THREAD

**Issue by LookSin** [sqlancer/sqlancer#704]
Hi！My local MySQL environment is 8.0.29. When I execute this command for testing, I find that the log file information generated in the target directory is less than the log information printed by the terminal. Is this normal?

**The command I executed：**
![image](https://user-images.githubusercontent.com/109679879/215261592-d4cb41c1-8bc2-433a-8e68-0c02e3b3c3d0.png)

**Logs in the target directory：**
![image](https://user-images.githubusercontent.com/109679879/215261754-98d28bf0-2c64-4118-84d2-38573d7de3d3.png)
**Logs printed by the terminal：**
![image](https://user-images.githubusercontent.com/109679879/215261891-05282ab7-06e0-4ad4-b17e-208d3e7c238c.png)
![image](https://user-images.githubusercontent.com/109679879/215261961-99e25e66-c639-4424-8a86-079289cad987.png)

**After comparison, I found that the same log terminal is printed twice consecutively, while the log file generated in the target directory is only displayed once. Is this information normal? Is the same command operation executed twice when Sqlancer is executed?**

**Comment by mrigger** [comment]
I assume you mean the `CREATE TABLE` statement? It is only executed once. The first part of the text output is the stack trace of the assertion error, and the second one (prefixed by `--`) is the log output which is the same as in the log file.

The reason for the error is btw that the latest MySQL version is not yet supported by SQLancer (see https://github.com/sqlancer/sqlancer/blob/354d591cfcd37fa1de85ec77ec933d5d975e947a/.github/workflows/main.yml#L252).

**Comment by LookSin** [comment]
OK，thank you for your answer very much!

**Comment by mrigger** [comment]
Thanks, we have now added a FAQ, which explains the issue (see https://github.com/sqlancer/sqlancer#faq).
