### ISSUE TITLE
Do you intend to add a full test workflow for StoneDB? (install StoneDB, run test, etc.)

### ISSUE THREAD

**Issue by shangyanwen** [sqlancer/sqlancer#719]
https://github.com/stoneatom/stonedb

**Comment by roxanne315** [comment]
How about support OpenGauss DB?
 https://gitee.com/opengauss/openGauss-server

**Comment by davidshiz** [comment]
> No concrete plans yet, but it would be great to support StoneDB in SQLancer. Would you be interested in adding such support, or would you like others to work on it (e.g., in this case, we could add it as a GSoC idea at https://github.com/sqlancer/sqlancer/wiki/GSoC-2023-Ideas#adding-support-for-and-testing-new-database-systems)?

good idea

**Comment by malwaregarry** [comment]
Support for StoneDB was added and subsequently removed as the project no longer seems to be maintained. We can revert the change and update our implementation of StoneDB if the development for StoneDB restarts.
