### ISSUE TITLE
Add issue template 

### ISSUE THREAD

**Issue by ZhengLin-Li** [sqlancer/sqlancer#742]
Currently our repo do not have a issue template.

GitHub supports Issue templates. Ref: [Issue template docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository).

The issue template will provide contributors with a structured entry point for reporting any issue or bug.

**Comment by yatharth-singh** [comment]
i  can fix this issue. please assign this to me

**Comment by mrigger** [comment]
I'm not convinced that having such a template is helpful, since we have a low number of issue reports, and little commonly required information (e.g., we currently don't even have regular releases).
