### ISSUE TITLE
Add comments to classes and methods

### ISSUE THREAD

**Issue by krishan30** [sqlancer/sqlancer#753]
I have a suggestion.As I going through the codes I noticed that most of classes didn't had any comments. I was thinking that adding comments may improve the code quality and may help to understand the codes very easily.Shall we add comments ? @mrigger

**Comment by mrigger** [comment]
I think strategic comments would be helpful, but writing the "right" comments is quite difficult without a detailed understanding of the codebase. Maintaining comments is also a potential cost. Thus, I'd prefer to avoid adding them (except if we can write good ones for some strategic places).

**Comment by krishan30** [comment]
I understand.Thank you for your guidance.I will then close this issue.
