### ISSUE TITLE
No program currently run `check_name.py`

### ISSUE THREAD

**Issue by ZhengLin-Li** [sqlancer/sqlancer#754]
It seams that there is no program currently run `check_name.py`

Do we need to run `check_name.py` in our CI to check our naming convention ?

**Comment by mrigger** [comment]
Great that you spotted this! Yes, it seems that after migrating from Travis to GitHub Actions (see https://github.com/sqlancer/sqlancer/pull/456/), this check "got lost". Do you want to try to re-add it? Perhaps https://github.com/sqlancer/sqlancer/blob/master/.github/workflows/main.yml#L13 is a good place for it.

**Comment by mrigger** [comment]
Fixed by https://github.com/sqlancer/sqlancer/pull/755.
