### ISSUE TITLE
Cnosdb: Inconsistent generated queries

### ISSUE THREAD

**Issue by Benxiaohai001** [sqlancer/sqlancer#761]
Inconsistent generated queries；
`--java.lang.AssertionError: database1: the results mismatch!
---- SELECT ALL MIN(m2.TIME), AVG(m2.f0) FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318);
---- result: 2129-04-18T17:19:06.474563560
---- SELECT MIN(agg0) FROM (SELECT MIN(m2.TIME)  as agg0 FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318) WHERE ((((lower(rpad(m2.t0, 1235214661, m0.t0)))||(((+ (1338135093))-(ascii(m2.t0))))))LIKE(((CAST( m2.f0 AS STRING))||(CAST( m2.t0 AS STRING))))) UNION ALL SELECT ALL MIN(m2.TIME)  as agg0 FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318) WHERE NOT (((((lower(rpad(m2.t0, 1235214661, m0.t0)))||(((+ (1338135093))-(ascii(m2.t0))))))LIKE(((CAST( m2.f0 AS STRING))||(CAST( m2.t0 AS STRING)))))) UNION ALL SELECT ALL MIN(m2.TIME)  as agg0 FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318) WHERE (((((lower(rpad(m2.t0, 1235214661, m0.t0)))||(((+ (1338135093))-(ascii(m2.t0))))))LIKE(((CAST( m2.f0 AS STRING))||(CAST( m2.t0 AS STRING)))))) IS NULL) as asdf;
---- result:
--      at sqlancer.cnosdb.oracle.tlp.CnosDBTLPAggregateOracle.aggregateCheck(CnosDBTLPAggregateOracle.java:78)
--      at sqlancer.cnosdb.oracle.tlp.CnosDBTLPAggregateOracle.check(CnosDBTLPAggregateOracle.java:43)
--      at sqlancer.common.oracle.CompositeTestOracle.check(CompositeTestOracle.java:22)
--      at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--      at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--      at sqlancer.Main$2.run(Main.java:559)
--      at sqlancer.Main$2.runThread(Main.java:541)
--      at sqlancer.Main$2.run(Main.java:532)
--      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
--      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
--      at java.base/java.lang.Thread.run(Thread.java:1589)
---- Time: 2023/03/13 15:51:06
-- Database: database1
-- Database version: {"version":"2.2.0, revision 12f21c37411afac4749c9c3ec347dab01fc52311","status":"healthy"}
-- seed value: 1678691888907
DROP DATABASE IF EXISTS database1;
CREATE DATABASE database1 WITH TTL '1000000' REPLICA 2;
CREATE TABLE m0(f0 BIGINT UNSIGNED , TAGS(t0));
CREATE TABLE m1(f0 DOUBLE , TAGS(t0, t1));
CREATE TABLE IF NOT EXISTS m2(f0 DOUBLE , TAGS(t0));
CREATE TABLE m3(f0 BIGINT UNSIGNED , TAGS(t0));
CREATE TABLE m4(f0 BOOLEAN , f1 DOUBLE , TAGS(t0, t1, t2));
INSERT m2(TIME, t0, f0) VALUES(CAST (7276521869176643097 AS TIMESTAMP), '/', 0.7051024665691711934556451524258591234683990478515625);
INSERT m2(TIME, t0, f0) VALUES(CAST (5026900746474563560 AS TIMESTAMP), '/', 0.00978065522405502374425623202114365994930267333984375);
INSERT m1(TIME, t0, f0, t1) VALUES(CAST (5026900746474563560 AS TIMESTAMP), '''s&gu⟨9', 5026900746474563584, '8
v8FM');
INSERT m2(TIME, t0, f0) VALUES(CAST (7463512649893071304 AS TIMESTAMP), '', 7463512649893070848), (CAST (7255331890043604862 AS TIMESTAMP), '0.7051024665691712', 0.163413504021133082488859145087189972400665283203125), (CAST (8319317966465604839 AS TIMESTAMP), '+So鸫', 0.7051024665691711934556451524258591234683990478515625);
INSERT m0(TIME, t0, f0) VALUES(CAST (933028718 AS TIMESTAMP), '8319317966465604839', 4278762065548520212), (CAST (7255331890043604862 AS TIMESTAMP), 'Bt', 7482161415621464733), (CAST (7276521869176643097 AS TIMESTAMP), '0.7051024665691712', 5113189404331185980);
INSERT m2(TIME, t0, f0) VALUES(CAST (6979432590115509703 AS TIMESTAMP), '', 0.59821902291969575315988549846224486827850341796875), (CAST (9208955083871911554 AS TIMESTAMP), '0.009780655224055024', 0.3197657301198428836386256080004386603832244873046875), (CAST (2202307455444592354 AS TIMESTAMP), '0.009780655224055024', 0.1126792734615327251646021977649070322513580322265625), (CAST (4385642229244192288 AS TIMESTAMP), '', 933028718), (CAST (6977325806844564742 AS TIMESTAMP), 'yG aɱhL﯏', 0.36251867795167014296708885012776590883731842041015625);
INSERT m1(TIME, t0, f0, t1) VALUES(CAST (6979432590115509703 AS TIMESTAMP), 'hEKy', 0.00978065522405502374425623202114365994930267333984375, '''s&gu⟨9');
-- SELECT ALL MIN(m2.TIME), AVG(m2.f0) FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318);
-- result: 2129-04-18T17:19:06.474563560
-- SELECT MIN(agg0) FROM (SELECT MIN(m2.TIME)  as agg0 FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318) WHERE ((((lower(rpad(m2.t0, 1235214661, m0.t0)))||(((+ (1338135093))-(ascii(m2.t0))))))LIKE(((CAST( m2.f0 AS STRING))||(CAST( m2.t0 AS STRING))))) UNION ALL SELECT ALL MIN(m2.TIME)  as agg0 FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318) WHERE NOT (((((lower(rpad(m2.t0, 1235214661, m0.t0)))||(((+ (1338135093))-(ascii(m2.t0))))))LIKE(((CAST( m2.f0 AS STRING))||(CAST( m2.t0 AS STRING)))))) UNION ALL SELECT ALL MIN(m2.TIME)  as agg0 FROM m0 LEFT OUTER JOIN m2 ON (((CAST( m0.f0 AS BIGINT))*(+ (-945184848)))) NOT IN (2085715318) WHERE (((((lower(rpad(m2.t0, 1235214661, m0.t0)))||(((+ (1338135093))-(ascii(m2.t0))))))LIKE(((CAST( m2.f0 AS STRING))||(CAST( m2.t0 AS STRING)))))) IS NULL) as asdf;
-- result: ;`

sql`SELECT ALL MIN(m2.TIME), AVG(m2.f0)
FROM m0
    LEFT JOIN m2 ON (CAST(m0.f0 AS BIGINT) * +-945184848) NOT IN (2085715318);
 
 
 SELECT MIN(agg0)
FROM (
    SELECT MIN(m2.TIME) AS agg0
    FROM m0
        LEFT JOIN m2 ON (CAST(m0.f0 AS BIGINT) * +-945184848) NOT IN (2085715318)
    WHERE (lower(rpad(m2.t0, 1235214661, m0.t0))
        OR +1338135093 - ascii(m2.t0)) LIKE (CAST(m2.f0 AS STRING)
        OR CAST(m2.t0 AS STRING))
    UNION ALL
    SELECT ALL MIN(m2.TIME) AS agg0
    FROM m0
        LEFT JOIN m2 ON (CAST(m0.f0 AS BIGINT) * +-945184848) NOT IN (2085715318)
    WHERE NOT (lower(rpad(m2.t0, 1235214661, m0.t0))
        OR +1338135093 - ascii(m2.t0)) LIKE (CAST(m2.f0 AS STRING)
        OR CAST(m2.t0 AS STRING))
    UNION ALL
    SELECT ALL MIN(m2.TIME) AS agg0
    FROM m0
        LEFT JOIN m2 ON (CAST(m0.f0 AS BIGINT) * +-945184848) NOT IN (2085715318)
    WHERE ((lower(rpad(m2.t0, 1235214661, m0.t0))
        OR +1338135093 - ascii(m2.t0)) LIKE (CAST(m2.f0 AS STRING)
        OR CAST(m2.t0 AS STRING))) IS NULL
) asdf;`

**Comment by mrigger** [comment]
I don't understand if this is a question, issue report, or feature request?
