### ISSUE TITLE
On the processing of error in table building statement

### ISSUE THREAD

**Issue by ChenglinTian** [sqlancer/sqlancer#762]
Hello, I have some doubts when using the latest version of sqlerer to detect duckdb. I use the latest version of duckdb with the version number of 0.7.0. But during the experiment, I found that almost all databases directly reported errors when executing the table creation statement. According to my understanding, once a database finds an error, it will immediately stop the execution of this database and start the next database.

However, this problem does not occur when using duck db 0.4.0. The table creation statement will continue to be executed even if there is a problem in the middle.

I want to know if you can help me solve this problem. Here are the errors I encountered

database0-cur.log
-- Time: 2023/03/14 22:43:57
-- Database: database0
-- Database version: v0.7.0
-- seed value: 1678804958671
CREATE TABLE t0(c0 DATE DEFAULT(981381004)); -- 0ms;
INSERT INTO t0(c0) VALUES (-1334081161); -- 0ms;
INSERT INTO t0(rowid, c0) VALUES (false, -830317102);

database0.log
--java.lang.AssertionError: INSERT INTO t0(rowid, c0) VALUES (false, -830317102);
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:109)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:93)
--	at sqlancer.Main$QueryManager.execute(Main.java:269)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
--	at sqlancer.StatementExecutor.executeStatements(StatementExecutor.java:70)
--	at sqlancer.duckdb.DuckDBProvider.generateDatabase(DuckDBProvider.java:122)
--	at sqlancer.duckdb.DuckDBProvider.generateDatabase(DuckDBProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:52)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:368)
--	at sqlancer.Main$2.run(Main.java:581)
--	at sqlancer.Main$2.runThread(Main.java:563)
--	at sqlancer.Main$2.run(Main.java:554)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:834)
--Caused by: java.sql.SQLException: java.sql.SQLException: Binder Error: Table "t0" does not have a column with name "rowid"
--	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:116)
--	at org.duckdb.DuckDBPreparedStatement.execute(DuckDBPreparedStatement.java:182)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:87)
--	... 13 more
--Caused by: java.sql.SQLException: Binder Error: Table "t0" does not have a column with name "rowid"
--	at org.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
--	at org.duckdb.DuckDBPreparedStatement.prepare(DuckDBPreparedStatement.java:106)
--	... 15 more
---- Time: 2023/03/14 22:43:57
-- Database: database0
-- Database version: v0.7.0
-- seed value: 1678804958671
CREATE TABLE t0(c0 DATE DEFAULT(981381004));
INSERT INTO t0(c0) VALUES (-1334081161);

**Comment by mrigger** [comment]
Hi, see https://github.com/sqlancer/sqlancer#i-am-running-sqlancer-on-the-latest-version-of-a-supported-dbms-is-it-expected-that-sqlancer-prints-many-assertionerrors for an answer to this.
