### ISSUE TITLE
SQLancer Website: Create a fully functional website.

### ISSUE THREAD

**Issue by aakarshee2000** [sqlancer/sqlancer#764]
**One of the main entities of SQLancer is their "Database". As far as the database is concerned, the database is responsible for: Fetching data (every day record should be accessible). Note: This will also include tests like - 
PQS randomly selects a pivot row, for which a query is generated that is guaranteed to pull the row. If the row is not contained in the result set, a bug is noted.
NoREC aims to find optimization bugs.
 TLP fragments a query into three partitioning queries, whose results are composed and  compared with respect to the original query's result set. A mismatch in the result sets logs a bug in the DBMS.(As mentioned in the readme.)
 **Generators 
 These are crucial in generating the data. There are two ways of doing this, The ways are as follows:
 Method 1: Random tables, foreign keys are generated post which the queries are randomly generated based on the schemas of the tables.
Method 2: Second one, QPG is a test case generation method driven by query plan coverage.(As mentioned in the readme)
So, all in all, we have 3 ways of testing the database and 2 ways of generating the database.
Apart from this "Bugs.json" also plays a significant role as it logs the mistakes made by the database. This also gives the measure of how good the database is.
Summary:
So, the basic working can be summarized as: Users take a database software like MySQL, mariadb, etc. Then they run a generator on it that creates tables and data. Generators are of 2 types. (Explained above) Then the users run some tests on the test database. Tests are of 3 types. (Explained above). This results in some logs that tell how good the database is. The logs need to be shown to the users nicely in the most Intuitive way possible for the best end user experiences.

Proposed Plan: So, we can have something like:
An instruction guide page: To help the users navigate easily over the website.
A functionality to select the type of generator.
A functionality to run the type of tests to run and a button to finally run.
A functionality to show the plots and tables.
A functionality to fetch the bugs from bugs.json and present it to the user.
All these can be on the same interface, as steps that appear one after the other. Finally, a page showing the most significant end results with a measure of how good the database is!

Kindly assign me this issue. Any feedbacks and suggestions are welcome.

**Comment by mrigger** [comment]
As explained on Slack, it would be useful to try to understand the purpose and functionality of SQLancer, as this summary is quite inaccurate.
