### ISSUE TITLE
SLF4J warning

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#77]
After merging https://github.com/sqlancer/sqlancer/pull/39, SQLancer now prints SLF4J warnings on startup:

```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar sqlite3
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[2020/07/01 09:22:57] Executed 150665 queries (30120 queries/s; 3.00/s dbs, successful statements: 92%). Threads shut down: 0.
```
@qoega do you have any ideas on how to fix this?

**Comment by qoega** [comment]
Yes. As it is written it tries to find one of logger implementations.
In my tests I added `<artifactId>slf4j-simple</artifactId>`, but it can be other as well

**Comment by mrigger** [comment]
Do you know how to prevent this warning when executing SQLancer outside a testing environment? Otherwise, I'll try to fix this.
