### ISSUE TITLE
bug: clickhouse duplicate expression in primary key

### ISSUE THREAD

**Issue by ZhengLin-Li** [sqlancer/sqlancer#788]
Our test statement, `CREATE TABLE IF NOT EXISTS T13_11TLPAggregate.t2 (c0 Int32) ENGINE = MergeTree()  ORDER BY max2(c0,c0);` results in an error in Clickhouse. 

Below is the result I tested on my machine. It says that "Primary key or secondary index contains a duplicate expression. To suppress this exception, rerun the command with setting 'allow_suspicious_indices = 1'. (BAD_ARGUMENTS) (version 23.5.1.1691 (official build))"

![image](https://github.com/sqlancer/sqlancer/assets/63448884/9af5318a-f9a6-4e8c-858e-e944dcabc75e)

The question is, why do we use `ORDER BY max2(c0,c0);`, It just does not make sense?

relevant CI error: https://github.com/sqlancer/sqlancer/actions/runs/5026419244/jobs/9014666964

**Comment by mrigger** [comment]
Perhaps the `max2(c0,c0)` in the `ORDER BY` is randomly generated? Not sure. @qoega, do you have an answer to this?

**Comment by qoega** [comment]
I need to fix 'allow_suspicious_indices' globally. I saw it in our CI.

**Comment by qoega** [comment]
https://github.com/sqlancer/sqlancer/pull/790

**Comment by qoega** [comment]
It should be fixed
