### ISSUE TITLE
Yugabyte CI ERROR: cannot use tablegroups in a colocated database

### ISSUE THREAD

**Issue by ZhengLin-Li** [sqlancer/sqlancer#789]
I have investigaed the Yugabyte CI error recently.

It seams our code violated the rules of Yugabute, resulting the failure of CI. Our code use use tablegroups in a colocated database which is not allow.

Please note the line 305 and line 324 in CI error log: https://github.com/sqlancer/sqlancer/actions/runs/5043922091/jobs/9046326765

Yugabute doc: https://github.com/yugabyte/yugabyte-db/blob/bc6682c0229447cfffc7bf8aa6c9d5deb7802ff2/architecture/design/ysql-tablegroups.md?plain=1#LL99C1-L99C1

I am considering fixing this currently and opened this issue for reference. Any comments on how to fix are welcome!

**Comment by mrigger** [comment]
Yes, I think one possible fix would be to prevent that both features are used at the same time in the table generator of Yugabyte.

**Comment by bajinsheng** [comment]
We can fix the commands to create databases in Yugabyte.
