### ISSUE TITLE
ClickHouse prints "Driver registered" on startup

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#80]
When launching SQLancer, a message is printed by the ClickHouse JDBC driver:
```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar sqlite3
[database9] INFO ru.yandex.clickhouse.ClickHouseDriver - Driver registered
[2020/07/01 22:20:07] Executed 133033 queries (26585 queries/s; 3.20/s dbs, successful statements: 92%). Threads shut down: 0.
```
@qoega do you know how we can disable this output?

**Comment by qoega** [comment]
I think it is better to switch from DriverManager to DataSource. I think it should help as JDBC drivers would be loaded only intentionally. 
https://docs.oracle.com/javase/8/docs/api/java/sql/DriverManager.html
`The use of a DataSource object is the preferred means of connecting to a data source.`
