### ISSUE TITLE
Value generated by SQLancer for jit_inline_above_cost is outside the correct range

### ISSUE THREAD

**Issue by nukoyluoglu** [sqlancer/sqlancer#86]
The command `SET SESSION jit_inline_above_cost=-134588496167444481;` was produced by SQLancer, which raises the error: `org.postgresql.util.PSQLException: ERROR: -1.34588e+17 is outside the valid range for parameter "jit_inline_above_cost" (-1 .. 1.79769e+308)`.

**Comment by mrigger** [comment]
Thanks for the report! This was a bug in the random number generation, which was (hopefully) fixed in https://github.com/sqlancer/sqlancer/pull/87.
