### ISSUE TITLE
CERT support/implementation for PostgreSQL

### ISSUE THREAD

**Issue by destrex271** [sqlancer/sqlancer#895]
**Proposal**: To implement the CERT testing technique presented in the following research paper: [https://arxiv.org/abs/2306.00355](https://arxiv.org/abs/2306.00355)  for PostgreSQL as well alongside the existing implementations for MySQL, Cockroach DB and TiDB.

**Comment by destrex271** [comment]
Can this issue be assigned to me? I have started the work on a patch for this feature.

**Comment by bajinsheng** [comment]
Sure. That would be great! Looking forward to your PRs!
