### ISSUE TITLE
Reducer doesn‘t work

### ISSUE THREAD

**Issue by Syang111** [sqlancer/sqlancer#898]
I ran the command below on ubuntu 20.04
> docker run -v $(pwd)/ran-tlp:/logs sqlancer --num-threads 4 --use-reducer --reduce-ast  sqlite3 --oracle QUERY_PARTITIONING 

but the **reduce directory were always empyt**, can anyone tell me what happened?

**Comment by ColinYoungTaro** [comment]
Currently the reducer only supports NoREC for sqlite3. 
For more details, you can refer to #890

**Comment by Syang111** [comment]
> Currently the reducer only supports NoREC for sqlite3. For more details, you can refer to #890
I see, thanks for your answers
