### ISSUE TITLE
sqlite logs : A malloc() failed (out of memory)  Exception

### ISSUE THREAD

**Issue by AlexWonga** [sqlancer/sqlancer#899]
Hello, 

I am using SQLancer to test version 3.43.2 of the SQLite database, and I have not made any modifications to the SQLancer files, only changing the version of SQLite. 

While running SQLancer, I noticed that all the log files generated by SQLancer have the same issue: [SQLITE_NOMEM] A malloc() failed (out of memory). I suspect that this is a bug in either SQLite or the SQLancer configuration.

Could you please assist me in resolving this issue？

![image](https://github.com/sqlancer/sqlancer/assets/52265703/1548bb7f-e7c6-443c-94b4-86967da856e8)

**Comment by AlexWonga** [comment]
When I run a lower version of SQLite, such as 3.41.0, it works perfectly.

**Comment by AlexWonga** [comment]
i use the command : java -jar sqlancer-2.0.0.jar --num-threads 20  sqlite3  --oracle NoREC

**Comment by mrigger** [comment]
It's likely that this is a bug in SQLite, unless a statement unexpectedly requires a lot of memory to execute (which didn't happen in the past). Can you reproduce this in the SQLite CLI when executing the statements from the log file(s)?

**Comment by AlexWonga** [comment]
hello, 
I have tried SQLite CLI and Python's SQLite version 3.43.2 and did not encounter any exceptions.
Here is the log files:
[database5.log](https://github.com/sqlancer/sqlancer/files/13264811/database5.log)
[database5-cur.log](https://github.com/sqlancer/sqlancer/files/13264809/database5-cur.log)

**Comment by bajinsheng** [comment]
Let me take a look.

**Comment by bajinsheng** [comment]
@AlexWonga There are three versions: 3.43.2.0, 3.43.2.1, 3.43.2,2 for the SQLite. Which one are you using?

**Comment by AlexWonga** [comment]
hello， I am using 3.43.2.0 and 3.43.0.0 two version

**Comment by AlexWonga** [comment]
![image](https://github.com/sqlancer/sqlancer/assets/52265703/c859ce30-4bad-4238-914d-76d32b60af4f)
I found this problem in 3.43.0.0 yesterday

**Comment by bajinsheng** [comment]
Ok. I can reproduce it. Investigating it soon.

**Comment by AlexWonga** [comment]
thank you very much!

**Comment by bajinsheng** [comment]
I think it is a bug and have reported to SQLite: https://sqlite.org/forum/forumpost/a655ee159e

**Comment by AlexWonga** [comment]
thank you!

**Comment by bajinsheng** [comment]
https://sqlite.org/forum/forumpost/506419a5c5a96f51 @AlexWonga The bug is confirmed and will be fixed soon. Please wait for the update of SQLite JDBC driver, so that you can avoid this bug in SQLancer. As a temporary solution, if this bug does not crash the SQLite, you can consider adding the error information here https://github.com/sqlancer/sqlancer/blob/main/src/sqlancer/sqlite3/SQLite3Errors.java#L20 to bypass this bug.

**Comment by AlexWonga** [comment]
thank you
