### ISSUE TITLE
Correct Naming Inconsistency in TestH2.java

### ISSUE THREAD

**Issue by AryanP45** [sqlancer/sqlancer#904]
While reviewing the test cases for understanding the SQLancer tool, I noticed a small typographical error in the [`TestH2.java`](https://github.com/sqlancer/sqlancer/blob/228dd53a75abe7f436fbe6090d53b3765a1459e0/test/sqlancer/dbms/TestH2.java)
 file. The existing test refers to "testDuckDB," but the intended reference is to H2 database, so I've updated it to "testH2DB."

## Current test :
```java
 @Test
    public void testDuckDB() {
        String h2Available = System.getenv("H2_AVAILABLE");
        boolean mariaDBIsAvailable = h2Available != null && h2Available.equalsIgnoreCase("true");
        assumeTrue(mariaDBIsAvailable);
        assertEquals(0, Main.executeMain(new String[] { "--random-seed", "0", "--timeout-seconds", TestConfig.SECONDS,
                "--num-threads", "4", "--num-queries", TestConfig.NUM_QUERIES, "h2" }));

    }
```

## Proposed Change :
```java
 @Test
    public void testH2DB() {
        String h2Available = System.getenv("H2_AVAILABLE");
        boolean h2DBIsAvailable = h2Available != null && h2Available.equalsIgnoreCase("true");
        assumeTrue(h2DBIsAvailable);
        assertEquals(0, Main.executeMain(new String[] { "--random-seed", "0", "--timeout-seconds", TestConfig.SECONDS,
                "--num-threads", "4", "--num-queries", TestConfig.NUM_QUERIES, "h2" }));

    }
```

- I have tested this change locally

> **Please let me know if this issue requires a separate pull request.**

**Comment by mrigger** [comment]
Thanks, it would be great if you could open a PR for that!
