### ISSUE TITLE
SQLancer Website

### ISSUE THREAD

**Issue by ayushkoli772** [sqlancer/sqlancer#906]
Hello @mrigger ,

I am writing this issue to express my interest and know the current progress of SQLancer website and what tech stack is/will be used for the website.

If anyone is currently working on this, then please let me be part of this. Im proficient in HTML, CSS, Javascript, Typrescript, Nodejs and Python.

If there is no progress on this then I would like to discuss and decide scope of the website.

Thank you for your time :)

**Comment by mrigger** [comment]
Thanks, we have already have one that is good enough at https://sqlancer.github.io/.

**Comment by ayushkoli772** [comment]
Got it. Thanks :)
