### ISSUE TITLE
Unable to test mysql8.0.36

### ISSUE THREAD

**Issue by Jondoe398** [sqlancer/sqlancer#913]
I have completed the test 'java -jar sqlancer-.jar --num-threads 4 sqlite3 --oracle NoREC' following the given steps, and everything is normal. After installing mysql8.0.36 and running 'java -jar sqlancer-.jar --num-threads 4 mysql --oracle FUZZER', I encountered the following error, and I also cannot specify the host and username. My environment is Ubuntu 20.04.
![微信截图_20240229160601](https://github.com/sqlancer/sqlancer/assets/104404517/7cc6a1ae-76db-499b-805c-c363f0224782)

**Comment by mrigger** [comment]
Please check https://github.com/sqlancer/sqlancer?tab=readme-ov-file#faq, where I believe your question is answered. If not, please reopen the issue and provide more detailed information on how you set up MySQL.
