### ISSUE TITLE
Make the host and port configurable

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#95]
Currently, the JDBC string containing the host name and port is hardcoded. For example, consider the connection string for MySQL:

https://github.com/sqlancer/sqlancer/blob/e62224edcb43fe421dc87601f75090739e34e595/src/sqlancer/mysql/MySQLProvider.java#L248

It would be desirable to make this configurable. We could provide an option to set the JDBC string for each DBMS. For example, for MySQL, the string could look like this:

```
"jdbc:mysql://$(HOST_NAME):$(PORT)/?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
```
We could then also provide two options to set the host name and port, which are then used to replace the placeholder in the JDBC string.

This would make everything configurable, but also be convenient for users. Most users could go with the default options. Some users might need to configure the port and host. Only very few users probably would need to change the JDBC query string.

**Comment by mrigger** [comment]
https://github.com/sqlancer/sqlancer/pull/133 implemented similar functionality for Postgres.

**Comment by Ethan-DB** [comment]
May I try it? If possible, please assign it to me.

**Comment by mrigger** [comment]
Yes, you are very welcome to work on this! As a heads up: I will be quite busy until March 17, so I might not have time to review pull requests or give feedback until after this date.

**Comment by Ethan-DB** [comment]
- [x] postgres
- [ ] MySQL

**Comment by EthanDBer** [comment]
Has this issue been resolved? May it be closed? @mrigger

**Comment by mrigger** [comment]
Yes, thanks for addressing this issue and for the reminder!
